import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/Components/Navbar/Navbar";
import Hero from "@/Components/Hero/Hero";
import BookingSection from "@/Components/Bookingsection/BookingSection";
import TrustSection from "@/Components/Trustsection/Trustsection";
import ScrollDivider from "@/Components/Scrolldivider/Scrolldivider";
import ServicesSection from "@/Components/Servicessection/Servicessection";
import WhyChooseSection from "@/Components/Whychoosesection/Whychoosesection";
import ReviewsSection from "@/Components/Reviewssection/Reviewssection";
import ContactSection from "@/Components/Contactsection/Contactsection";
import Footer from "@/Components/Footer/Footer";
import ScrollProgressBar from "@/Components/Scrollprogressbar/Scrollprogressbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ScrollProgressBar />
      <div>
        <Navbar />
        <Hero />
        <BookingSection />
        {/* <ScrollDivider /> */}
        <TrustSection />
        <ServicesSection />
        <WhyChooseSection />
        <ReviewsSection />
        <ContactSection />
        <Footer />
      </div>
    </>
  );
}
